source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               lib/maddi-ide-client.jar,\
               lib/jackson-databind.jar,\
               lib/jackson-core.jar,\
               lib/jackson-annotations.jar
